version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx_compose_v3
    networks:
      nginx_network:
        ipv4_address: 192.168.1.1
networks:
  nginx_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
